name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.11
        with:
          heroku_api_key: "8ca3bf77-deb5-48fb-b021-5ada2187e9b1"
          heroku_app_name: "young-citadel-75478"
          heroku_email: "vienna.borowska@hotmail.com"
